import Head from "next/head";
import SocialMedia from "../../components/SocialMedia";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vedant Next App | Awesome Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mainWrapper">{/* <SocialMedia /> */}</main>
    </>
  );
}
